
module.exports = [
{term:"MÜQAYİSƏ",desc:"İki və ya daha çox obyektin oxşar və fərqli tərəflərinin öyrənilməsi"},
{term:"KONTEKST",desc:"Tədqiqatın aparıldığı mühit və şərait"},
{term:"METODOLOGİYA",desc:"Tədqiqatın aparılması üçün istifadə olunan metodlar sistemi"},
{term:"KƏMİYYƏT",desc:"Rəqəmlərlə ölçülən məlumatlara əsaslanan yanaşma"},
{term:"KEYFİYYƏT",desc:"Müşahidə və interpretasiyaya əsaslanan metod"},
{term:"SORĞU",desc:"Respondentlərdən məlumat toplamaq üsulu"},
{term:"ANKET",desc:"Sorğu üçün hazırlanmış suallar forması"},
{term:"RESPONDENT",desc:"Sorğuda iştirak edən şəxs"},
{term:"HIPOTEZ",desc:"Araşdırma zamanı yoxlanılan ehtimal"},
{term:"NƏZƏRİYYƏ",desc:"Elmi şəkildə izah edən konsepsiya"},
{term:"STATİSTİKA",desc:"Məlumatların rəqəmsal analizi"},
{term:"ANALİZ",desc:"Məlumatların təhlil prosesi"},
{term:"MÜŞAHİDƏ",desc:"Hadisələrin birbaşa izlənməsi"},
{term:"EKSPERİMENT",desc:"Şərtlərin dəyişdirilməsi ilə aparılan test"},
{term:"NÜMUNƏ",desc:"Populyasiyanı təmsil edən kiçik qrup"},
{term:"POPULYASİYA",desc:"Araşdırılan bütün obyektlər toplusu"},
{term:"KORELYASİYA",desc:"İki dəyişən arasındakı əlaqə"},
{term:"ETİBARLILIQ",desc:"Ölçmənin sabitliyi"},
{term:"DƏQİQLİK",desc:"Ölçmənin həqiqətə yaxınlığı"},
{term:"SİSTEM",desc:"Bir-biri ilə əlaqəli elementlər toplusu"},
{term:"MODEL",desc:"Reallığın sadələşdirilmiş təsviri"},
{term:"STRATEGİYA",desc:"Məqsədə çatmaq üçün plan"},
{term:"TƏDQİQAT",desc:"Elmi araşdırma prosesi"},
{term:"METOD",desc:"Araşdırma üsulu"},
{term:"VARİABL",desc:"Dəyişə bilən amil"},
{term:"MÜQAYİSƏLİ",desc:"İki və ya daha çox obyektin qarşılaşdırılması"},
{term:"KEYS",desc:"Tək hadisənin dərin analizi"},
{term:"KRİTERİYA",desc:"Qiymətləndirmə ölçüsü"},
{term:"MƏNBƏ",desc:"Məlumatın əldə olunduğu yer"},
{term:"SİTEZ",desc:"Məlumatların birləşdirilməsi"},
{term:"INTERPRETASİYA",desc:"Məlumatın mənalandırılması"},
{term:"DƏYİŞƏN",desc:"Araşdırmada ölçülən amil"},
{term:"PARAMETR",desc:"Sistemin xüsusiyyəti"},
{term:"TƏHLİL",desc:"Detallı analiz prosesi"},
{term:"TENDENSİYA",desc:"Meyl və istiqamət"},
{term:"PROSES",desc:"Ardıcıl hadisələr zənciri"},
{term:"STRUKTUR",desc:"Elementlərin quruluşu"},
{term:"FUNKSİYA",desc:"Elementin yerinə yetirdiyi rol"},
{term:"MEXANİZM",desc:"Prosesin işləmə prinsipi"},
{term:"FAKTOR",desc:"Təsir edən amil"},
{term:"GÖSTƏRİCİ",desc:"Ölçü indikatoru"},
{term:"DİNAMİKA",desc:"Zaman üzrə dəyişmə"},
{term:"NƏTİCƏ",desc:"Araşdırmanın əldə etdiyi yekun"},
{term:"TƏSDİQ",desc:"Hipotezin doğrulanması"},
{term:"İNTERVYU",desc:"Şifahi sorğu metodu"},
{term:"FOKUSQRUP",desc:"Qrup müzakirəsi metodu"},
{term:"OBSERVASİYA",desc:"Müşahidə metodu"},
{term:"METODLAR",desc:"Araşdırma üsullarının toplusu"},
{term:"SİSTEMLİK",desc:"Məntiqi ardıcıllıq"},
{term:"KONSEPSİYA",desc:"Əsas ideya sistemi"}
]
